// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1djpC1IMGdnXKgNr3kpk0q9iUt47tkpU',
    appId: '1:255895537193:web:a5ed928b71c374bc14be38',
    messagingSenderId: '255895537193',
    projectId: 'triot-d7e6e',
    authDomain: 'triot-d7e6e.firebaseapp.com',
    databaseURL: 'https://triot-d7e6e-default-rtdb.firebaseio.com',
    storageBucket: 'triot-d7e6e.appspot.com',
    measurementId: 'G-KK70TG4BHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4zo6HEBFXWx0alkH_gWhl3dHkbj5EhYM',
    appId: '1:255895537193:android:ac136545e0dc400a14be38',
    messagingSenderId: '255895537193',
    projectId: 'triot-d7e6e',
    databaseURL: 'https://triot-d7e6e-default-rtdb.firebaseio.com',
    storageBucket: 'triot-d7e6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-t7Ui0qRTIFRIMbaX8cC9NQk80RfjkU8',
    appId: '1:255895537193:ios:9eb9c5ca8bc6c8ac14be38',
    messagingSenderId: '255895537193',
    projectId: 'triot-d7e6e',
    databaseURL: 'https://triot-d7e6e-default-rtdb.firebaseio.com',
    storageBucket: 'triot-d7e6e.appspot.com',
    iosClientId: '255895537193-e9ak7v71juden0hh586a3ufddkql2jtm.apps.googleusercontent.com',
    iosBundleId: 'com.example.trflutterbasicsketch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-t7Ui0qRTIFRIMbaX8cC9NQk80RfjkU8',
    appId: '1:255895537193:ios:9eb9c5ca8bc6c8ac14be38',
    messagingSenderId: '255895537193',
    projectId: 'triot-d7e6e',
    databaseURL: 'https://triot-d7e6e-default-rtdb.firebaseio.com',
    storageBucket: 'triot-d7e6e.appspot.com',
    iosClientId: '255895537193-e9ak7v71juden0hh586a3ufddkql2jtm.apps.googleusercontent.com',
    iosBundleId: 'com.example.trflutterbasicsketch',
  );
}
